openapi: 3.0.0
info:
  title: Lark Open Platform
  description: Lark Open Platform Postman
  version: 1.0.0
servers:
  - url: https://{{baseurl}}
  - url: https://open.feishu.cn
  - url: http://{{base_url}}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: Docs > Sheets
  - name: Docs > Sheets > spreadsheet
paths:
  /sheets/v3/spreadsheets:
    post:
      tags:
        - Docs > Sheets > spreadsheet
      summary: Create spreadsheet
      description: "Use this API to create an online spreadsheet under the specified directory.\r\n\r\nAPI reference documentation: [Create spreadsheet]({{document_base_url}}/ukTMukTMukTM/uUDN04SN0QjL1QDN/sheets-v3/spreadsheet/create)"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                folder_token: fldcnMsNb*****hIW9IjG1LVswg
                title: title
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}